version: "2.1"
services:

    asterisk:
        image: callcenter.asterisk.dev
        container_name: dev-asterisk
        build:
            context: docker
            dockerfile: asterisk/Dockerfile
        ports:
        - "5060:5060/udp"
        - "39000-40000:39000-40000/udp"
networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: 172.25.0.0/16